[package]
name = "orqadence"
version = "1.4.10"
edition = "2021"
rust-version = "1.89"
license-file = "LICENSE.md"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crossterm = "0.29"
ratatui = "0.30"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "3.4.2", default-features = false, features = ["rustls"] }

[[bin]]
name = "orqa"
path = "src/main.rs"
